/*
 * Generated by MTK SP DrvGen Version: 3.5.160809 for MT6893.
 * 2023-06-02 17:19:58
 * Do Not Modify The File.
 * Copyright Mediatek Inc. (c) 2016.
*/

#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/upmu_common.h>
#include <mach/upmu_hw.h>
#include <mach/mt_pm_ldo.h>

void pmu_drv_tool_customization_init(void)
{
	pmic_set_register_value(PMIC_RG_LDO_VCAMIO_EN,0);
	pmic_set_register_value(,0);
}
